# Generated by Django 5.2.5 on 2025-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('web', 'Web Development'), ('data', 'Data Science'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Danh mục'),
        ),
    ]
