# Generated by Django 5.2.5 on 2025-08-30 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_forumpost_postcomment_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weeks', models.IntegerField(default=4, verbose_name='Tổng số tuần')),
                ('hours_per_week', models.IntegerField(default=5, verbose_name='Số giờ/tuần')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='Tuần thứ')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tuần')),
                ('objectives', models.TextField(verbose_name='Mục tiêu học tập')),
                ('total_hours', models.IntegerField(default=5, verbose_name='Tổng giờ học')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='courses.learningpath')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='Ngày thứ')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Thời gian (phút)')),
                ('resources', models.TextField(blank=True, verbose_name='Tài liệu tham khảo')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Hoàn thành')),
                ('weekly_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='courses.weeklyschedule')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
