# Generated by Django 5.2.5 on 2026-01-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_learningpath_weeklyschedule_dailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
    ]
