# Generated by Django 5.2.5 on 2026-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_orderitem_order_remove_orderitem_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Tập tin đính kèm'),
        ),
    ]
